### ISSUE TITLE
Triggers that are not described in the paper

### ISSUE THREAD

**Issue by VoodooChild99** [MCUSec/SEmu#6]
Hi,

I notice that some triggers are not described in the paper. For example, the L-trigger in rules extracted from the F429 manual:
https://github.com/MCUSec/SEmu/blob/main/RuleExtraction/extractedRules/f429.txt#L1281

These triggers seem to be related to the ETH peripheral. Could you please explain the meanings of these triggers?

Thanks!

**Comment by Moirai7** [comment]
Thanks for reaching out! The L-trigger is designed for Eth. It means the descriptor located in the value of certain register.
For example,
L,0x4002900c,46,=,1->0x4002900c,60/59/58/57/56/55/54/53/52/51/50/49/48,=,0
The descriptor is located in the value of register 0x4002900c, and if the descriptor at bit 46 is 1, the corresponding bits in register 0x4002900c should be set as 0.

**Comment by shandianchengzi** [comment]
> Hi,
> 
> I notice that some triggers are not described in the paper. For example, the L-trigger in rules extracted from the F429 manual: https://github.com/MCUSec/SEmu/blob/main/RuleExtraction/extractedRules/f429.txt#L1281
> 
> These triggers seem to be related to the ETH peripheral. Could you please explain the meanings of these triggers?
> 
> Thanks!

Thanks for reaching out! The other L rules mean different conditions when dealing with the Eth.

You can see this code for the usage of LC: https://github.com/IoTS-P/SEmu-Fuzz/blob/67e30eae6737ed88335c147c21b43a8fb09b9e04/semu_fuzz/emulate/semu/rule.py#L522-L529
For example,
`LC,*->0,31,=,1`    means    "Check RDS0[31] = 1". If RDS0[31] != 1, hardware will not write to the descriptor because RDES0 hasn't been init.
`LC,*->8,*,>,0`    means   "Check RDES2[*] > 0". If RDES2 <= 0, hardware will not write to the descriptor because RDES2 hasn't been init.

You can see this code for the usage of LO, LE, LF: https://github.com/IoTS-P/SEmu-Fuzz/blob/67e30eae6737ed88335c147c21b43a8fb09b9e04/semu_fuzz/emulate/semu/rule.py#L557-L565
For example,
`LO,*->0,31,=,0`    means    "let RDS0[31]=1"
`LO,*->4,14,=,1`    means    "let RDS1[14]=1"
`LE,*->0,8,=,1`    means    "let RDS0[8]=1". This rule is only active when the descriptor is the end descriptor.
`LE,*->4,15,=,1`    means    "let RDS1[15]=1". This rule is only active when the descriptor is the end descriptor.
`LF,*->0,9,=,1`    means    "let RDS0[9]=1". This rule is only active when the descriptor is the first descriptor.
In fact, the function of LO,LE,LF is the same. The only difference from them is trigger location.

**Comment by VoodooChild99** [comment]
Thanks for the reply! Guess I'll have to read more code :)
